<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>es8新特性</title>
	</head>
	<body>
		<script>
			/**
			 * async和await结合可以让异步代码像同步代码一样
			 */
			
			
			//async函数，它的返回值永恒是一个Promise对象
			async function fn() {
				/**
				 * async函数的返回值，有三种情况
				 * 		1.如果返回的不是Promise对象，那么返回的就是成功的Promise对象的值
				 * 		2.如果抛出异常throw new Error()，那么返回的就是一个失败的Promise
				 *  	3.如果返回的是一个Promise对象，则Promise的返回结果就是函数的返回结果
				 */
				//第一种情况
				// return 'success'  //此时返回的是一个成功的Promise，并且Promise的值为success
				
				//第二种情况
				// throw new Error('fail') //此时返回的是一个失败的Promise，并且Promise的值为fail
				
				//第三种情况，此时函数的返回结果由Promise对象来决定，并且跟随Promise的返回结果
				return new Promise((resolve, reject) => {
					//成功
					resolve('success')
					
					//失败
					// reject('fail')
				})
			}
			
			//执行函数
			const p = fn()
			//由于返回的是一个Promise对象，所以可以使用then方法处理结果
			p.then(
				result => {
					console.log(result)
				},
				res => {
					console.warn(res)
				}
			)
			
			
			/**
			 * await函数
			 * 		1. await必须要写在async函数中，但是async函数中可以没有async，这就类似于java中的抽象类一个道理
			 * 		2. await右侧的表达式一般为Promise对象
			 * 		3. await返回的是Promise成功的值
			 * 		4. await的Promise失败了，就会抛出异常，需要通过try...catch捕获处理
			 */
			const p1 = new Promise((resolve, reject) => {
				//成功
				// resolve({
				// 	name: '张三',
				// 	age: 12,
				// 	sex: '男'
				// })
				
				//失败
				reject({
					code: -1,
					msg: '出现错误，系统异常！'
				})
			})
			async function getPerson() {
				try{
					//成功
					let result = await p1
					console.log(result)
				}catch(e){
					//失败
					console.log(e)
				}
			}
			//调用函数
			getPerson()
		</script>
	</body>
</html>
